clone:
  depth: 2

definitions:
  steps:
    - step: &check-code
        name: Check code
        image: "herloct/phpcs"
        script:
          - "php -v"
          - "phpcs --standard=PSR12 app/"

    - step: &deploy-to-prod
        name: Deploy to prod
        image: rdoepner/docker-deployer:7.2
        deployment: production
        trigger: automatic
        size: 2x
        script:
          - deployer --version
          - eval "$(ssh-agent -s)"
          - ssh-add ~/.ssh/id_pipelines
          - deployer deploy prod

pipelines:
  branches:
    master:
      - step: *deploy-to-prod

    develop:
      - step: *check-code

  pull-requests:
    develop:
      - step: *check-code
