clone:
  depth: 2

pipelines:
  branches:
    master:
      - step:
          image: rdoepner/docker-deployer:7.2
          script:
            - deployer --version
      - step:
          name: Deploy to production
          image: rdoepner/docker-deployer:7.2
          deployment: production
          trigger: automatic
          size: 2x
          script:
            - eval "$(ssh-agent -s)"
            - ssh-add ~/.ssh/id_pipelines
            - deployer deploy prod

    develop:
      - step:
          name: Check codestyle
          image: "herloct/phpcs"
          script:
            - "php -v"
            - "phpcs --standard=PSR12 app/"

  pull-requests:
    develop:
      - step:
          name: Check codestyle
          image: "herloct/phpcs"
          script:
            - "php -v"
            - "phpcs --standard=PSR12 app/"
